sudo: required
services: 
  - docker

before_install:
  - docker build -t mercierv/complex-test -f ./client/Dockerfile.dev .

language: generic

script:
  - docker run -e CI=true mercierv/complex-test npm run test