sudo: required
services: 
  - docker

before_install:
  - docker build -t mercierv/complex -f ./client/Dockerfile.dev ./client

language: generic

script:
  - docker run -e CI=true mercierv/complex npm run test

after_success:
  - docker build -t mercierv/complex-client ./client
  - docker build -t mercierv/complex-nginx ./nginx
  - docker build -t mercierv/complex-server ./server
  - docker build -t mercierv/complex-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push mercierv/complex-client
  - docker push mercierv/complex-nginx
  - docker push mercierv/complex-server
  - docker push mercierv/complex-worker